def dbutils.fs.mount(source: str, mountPoint: str, encryptionType: Optional[str], extraConfigs: Optional[Map]): ...

def dbutils.fs.put(file: str, contents: str, overwrite: Optional[bool]) -> bool: ...
